### ISSUE TITLE
Need to be able to exclude actions in a controller

### ISSUE THREAD

**Issue by joelbyler** [CultivateHQ/basic_auth#16]
Currently I will need to have a separate controller if I have some actions which need to be secured and others which don't.  It would be great if I could use the same controller for both and differentiate them by an `except` or `only` option.  

Possible Example:
```elixir
plug BasicAuth, use_config: { :your_app, :your_key, except: [:index] }
```

**Comment by joelbyler** [comment]
Actually, I think I figured out how do do this myself using the syntax below

```
plug BasicAuth, [use_config: {: your_app, : your_key}] when not action in [: index]
```

And to authenticate on only a single action, you can drop the `not` like so

```
plug BasicAuth, [use_config: {: your_app, : your_key}] when action in [: delete]
```

**Comment by joelbyler** [comment]
@paulanthonywilson I can submit a PR to add this to the README if you feel it would be of benefit to others?  Otherwise I'll just add it to my own personal TIL list for today.

**Comment by paulanthonywilson** [comment]
@joelbyler That PR would be great, @joelbyler. Thanks.

(Sorry, only noticed this issue when you mentioned me; I need to get my notifications sorted out.)

**Comment by joelbyler** [comment]
@paulanthonywilson please have a look at #17 I'm up for any feedback you have on it.  Thanks!
