### ISSUE TITLE
No WWW-Authenticate header after callback

### ISSUE THREAD

**Issue by vassilevsky** [CultivateHQ/basic_auth#19]
Hi! I'm new to Elixir. Excuse me if this is not a problem with this library.

I used the `callback:` option and the server did not return the `WWW-Authenticate` header.

I noticed that it is not sent in one of the functions. Why is that so?

I tried adding it to the `conn` myself inside the callback but it didn't make a difference.

**Comment by paulanthonywilson** [comment]
@vassilevsky sorry for the delay.

Do you have any example code that you could show to illustrate the problem?

**Comment by vassilevsky** [comment]
Sure.

I added the plug here:

https://github.com/vassilevsky/flutube/blob/36e2c0187b95a18d0e10209e54fc28fd554c43ba/web/controllers/talk_controller.ex#L6

And wrote a simple module for the callback:

https://github.com/vassilevsky/flutube/blob/36e2c0187b95a18d0e10209e54fc28fd554c43ba/lib/heimdall.ex

It did return 401 but the browser did not ask for credentials.

There are two different functions in the library:

1. The one that returns the header:

https://github.com/CultivateHQ/basic_auth/blob/master/lib/basic_auth.ex#L114

2. And the one that doesn't:

https://github.com/CultivateHQ/basic_auth/blob/master/lib/basic_auth.ex#L119-L123

I figured that the second one was called in my case. But I couldn't figure out why.

In the end I just wrote the entire auth plug myself, using this library as a reference:

https://github.com/vassilevsky/flutube/blob/master/lib/heimdall.ex

So I am thankful to you in any case!

**Comment by paulanthonywilson** [comment]
Hi @vassilevsky. Yes, it's a problem with a realm not being provided. There's a fix here, https://github.com/CultivateHQ/basic_auth/pull/20, that should sort it out.

Thanks for bringing it up.

**Comment by paulanthonywilson** [comment]
Fixed in https://github.com/CultivateHQ/basic_auth/pull/20, and released patch version to Hex.
