### ISSUE TITLE
Response content type not set in BasicAuth.Response.unauthorise/2

### ISSUE THREAD

**Issue by scottswezey** [CultivateHQ/basic_auth#30]
When using this plug and canceling out of the browser authentication box in Safari, Safari downloads a file rather than display the 401 error message. I believe this is caused by the lack of a response content type being set, and solved by adding `Plug.Conn.put_resp_content_type("text/plain")` before `Plug.Conn.send_resp(401, "401 Unauthorized")`.

The change is quite simple, but I would be happy to submit a pull request if you would like to consider the change.

**Comment by scottswezey** [comment]
I've forked the repo and made a PR there: https://github.com/scottswezey/basic_auth/pull/1

Let me know if I should propose the PR here as well.

**Comment by paulanthonywilson** [comment]
Thanks @scottswezey. TBH we're not seeing the issue, even with my Safari 11.0, but I do believe you. Adding the header seems like a good idea, in any case. Please submit the PR.

**Comment by scottswezey** [comment]
Thanks. PR created. See #31 

Let me know if you would like any changes on my end.

**Comment by paulanthonywilson** [comment]
Merged. Thank you.  We'll release a patch version later.
