### ISSUE TITLE
Anyway I can use this in Phoenix router definition?

### ISSUE THREAD

**Issue by ChrisZou** [CultivateHQ/basic_auth#34]
Hi @paulanthonywilson , 
First of all, thank you so much for making this library. It has been great help for me.
I wonder if could use this in my Phoenix router definition? I would like to apply basic auth for a certain router scope, so that I don't have to write the plug code in every controller under that scope.
Sort of like this.

```elixir
defmodule MyApp.Router do
  use MyApp, :router

  pipeline :admin_auth do
    plug(:basic_auth, ...)
  end

  scope "/admin", as: :admin do
    pipe_through([:browser, :admin_auth])
    # My router definition
  end
```

Thank you!

**Comment by picandocodigo** [comment]
Hi @ChrisZou,
You can use it in a Phoenix router definition. I've used it like this in a Phoenix app's router:
```elixir
pipeline :authentication do
  plug BasicAuth, use_config: {:web, :authentication}
end

scope "/", Web do
  pipe_through [:browser, :authentication]

  get "/", PageController, :index
end
```

And I used it in a learning project with a similar example [here](https://github.com/picandocodigo/us_airports_weather/blob/master/lib/weather_web/router.ex).

**Comment by paulanthonywilson** [comment]
Seems to be covered.

**Comment by ChrisZou** [comment]
@picandocodigo Thank you! It works. I guess I don't understand plug enough. 😅  Would be nice if it's in the README for Elixir beginners like me.
