### ISSUE TITLE
Request for changelog

### ISSUE THREAD

**Issue by axelson** [CultivateHQ/basic_auth#37]
Is it possible to create a changelog (maybe at least going forward) for this library. I'm currently using version 1.0.0 of this library. Is there a listing of the changes to the current version (2.2.2)?

**Comment by paulanthonywilson** [comment]
We now have such a thing. Thanks for the suggestion @axelson

**Comment by axelson** [comment]
Awesome, thanks! I find them extremely helpful when I'm updating depedencies.
