### ISSUE TITLE
Update cowboy dependency to 2.x

### ISSUE THREAD

**Issue by ericlathrop** [CultivateHQ/basic_auth#38]
I was looking to update cowboy in one of my projects, and it's blocked by `basic_auth`. Would you accept a PR for cowboy 2.x support?

I found a fork where someone started this work: https://github.com/NineFX/basic_auth

**Comment by paulanthonywilson** [comment]
Yes, we would. Been meaning to take a look at updating for that.

**Comment by m45t3r** [comment]
@paulanthonywilson One suggestion: can you simply remove the dependency on cowboy?

This library seems to only depend on `plug` API itself. In one project that I am working now, setting `{:cowboy, "~> 2.0", override: true}` works. BTW, `plug` may support other HTTP servers, it is just for now it only supports `cowboy 1.x` and `cowboy 2.x`.

**Comment by m45t3r** [comment]
@paulanthonywilson I just created a PR with the change [I commented above](https://github.com/CultivateHQ/basic_auth/issues#issuecomment-414128403): https://github.com/CultivateHQ/basic_auth/pull/40

Instead of removing `cowboy` completely from the dependency list, I set it only in `:dev` and `:test` environments, since `cowboy` is necessary to run the tests. Running a `mix hex.build` after the change seems to get the desired result:

Before:
```
Building basic_auth 2.2.2
  Dependencies:
    cowboy ~> 1.0 (app: cowboy)
    plug ~> 0.14 or ~> 1.0 (app: plug)
  App: basic_auth
  Name: basic_auth
  Files:
    lib
    lib/basic_auth
    lib/basic_auth.ex
    lib/basic_auth/configured.ex
    lib/basic_auth/response.ex
    lib/basic_auth/with_callback.ex
    LICENSE.md
    mix.exs
    README.md
  Version: 2.2.2
  Build tools: mix
  Description: Basic Authentication Plug
  Licenses: MIT
  Links: 
    github: https://github.com/cultivatehq/basic_auth
  Elixir: ~> 1.0
Package checksum: d2ce0c5336ea4544c1a3a1542ad70c7f2e3f67d08fb0d2494355d337d6a027db
```

After:
```
Building basic_auth 2.2.2
  Dependencies:
    plug ~> 0.14 or ~> 1.0 (app: plug)
  App: basic_auth
  Name: basic_auth
  Files:
    lib
    lib/basic_auth
    lib/basic_auth.ex
    lib/basic_auth/configured.ex
    lib/basic_auth/response.ex
    lib/basic_auth/with_callback.ex
    LICENSE.md
    mix.exs
    README.md
  Version: 2.2.2
  Build tools: mix
  Description: Basic Authentication Plug
  Licenses: MIT
  Links: 
    github: https://github.com/cultivatehq/basic_auth
  Elixir: ~> 1.0
Package checksum: 2121ea549204cce6619d7245c377651c1a3fbc55d2d77b337417adf1fddb6cb8
```

**Comment by paulanthonywilson** [comment]
Dealt with by https://github.com/CultivateHQ/basic_auth/pull/40 . Thanks @m45t3r
