### ISSUE TITLE
Adding credentials to the config

### ISSUE THREAD

**Issue by nathanhornby** [CultivateHQ/basic_auth#4]
This may be due to changes in the framework in the past few months, however the config examples provided aren't getting me very far unfortunately.

**Important note:** I'm still learning Elixir and Phoenix - so I apologise for any obvious oversights.

This is what I'm getting when running `mix test`:

```
You have configured application :admin_basic_auth in your configuration
file but the application is not available.

This usually means one of:

1. You have not added the application as a dependency in a mix.exs file.

2. You are configuring an application that does not really exist.

Please ensure :admin_basic_auth exists or remove the configuration.
```

This is using the example provided in the readme:

`config :admin_basic_auth, realm: "Admin", username: "admin", password: "password"``

If I work out what's going wrong before anyone sees this issue, I'll get a pull request in for the readme.

**Comment by nathanhornby** [comment]
OK so I've gotten a little further, but I'm struggling to get both the tests and the dev site both working (which seems odd), it's either one or the other.

Firstly I needed to change a lot of references from `:admin_basic_auth`to `:basic_auth` (I believe that's the crux of my original error, that the app name is wrong).

_However_ that only gets the dev site working. Making that change everywhere breaks the tests. Bizarrely I need `plug BasicAuth, use_config: :admin_basic_auth`for the plug for the tests to work, even though `:admin_basic_auth`is no longer referencing any actual configuration. And this prevents the real site from authorising properly.

Any idea about those inconsistencies? I'm new to the language and framework and am ore than stumped.

**Comment by mconnell** [comment]
Hi, sorry you've been having issues. The documentation did fall behind a little bit after a change was merged to handle deploying to environments like heroku. There was a pull request with some README changes (https://github.com/CultivateHQ/basic_auth/pull/3/files) I've just merged in. Can you give them a shot and let me know if you're still having problems?

**Comment by nathanhornby** [comment]
Thanks @mconnell I'll take a look, I think I've narrowed my issue to a problem with:

`@username Application.get_env(:Nhby, :basic_auth)[:username]`
(and the password)

**Comment by mconnell** [comment]
Cool, glad it helped :) I'll close this issue for just now, but please do PR anything if you spot something that can be improved. Thanks!
