### ISSUE TITLE
Support runtime credential configuration

### ISSUE THREAD

**Issue by ericlathrop** [CultivateHQ/basic_auth#7]
Both the config file and the router's `plug` line are executed at compile time, only storing environment variables when the system is built.

I would like it if basic_auth supported a `{:system, "ENV_VAR"}` similar to Phoenix so the values can be configured at run time. See http://hexdocs.pm/phoenix/Phoenix.Endpoint.html:

> The `:port` option requires either an integer, string, or `{:system, "ENV_VAR"}`. When given a tuple like `{:system, "PORT"}`, the port will be referenced from `System.get_env("PORT")` at runtime as a workaround for releases where environment specific information is loaded only at compile-time.

**Comment by ericlathrop** [comment]
Ideally the `{:system, "ENV_VAR"}` convention will eventually be built into Elixir's `Application` module so each individual application doesn't have to be patched to support this.

**Comment by cazrin** [comment]
That sounds like a great idea @ericlathrop. I know the maintainers are pretty busy, so I'm sure they'd appreciate a PR for this if you have the time to do so. Otherwise I can see if I'm able to do it at some point :)

**Comment by vitalis** [comment]
@ericlathrop right now you can do the following setup:
in `Router`
```elixir
plug BasicAuth, use_config: :basic_auth
```

in `prod.exs`
```elixir
config :basic_auth,
  realm: "Admin Area",
  username: System.get_env("BASIC_AUTH_USER"),
  password: System.get_env("BASIC_AUTH_PASSWORD")
```

**Comment by ericlathrop** [comment]
@vitalis Correct, but what you may not realize is that the config file is converted to an erlang `sys.config` file at the time you build a release, so the `System.get_env/1` calls are only executed at build time.

**Comment by binaryseed** [comment]
This is already possible when using an OTP release...

Set the config like this: 

```elixir
config :otp_app, key: "${ENV_VAR}"
```

Then, when booting, set `RELX_REPLACE_OS_VARS=true`. This will pull in the value of `ENV_VAR` at runtime instead of compile time

See: http://blog.plataformatec.com.br/2016/05/how-to-config-environment-variables-with-elixir-and-exrm/

**Comment by mbuhot** [comment]
This feature would be very helpful for me.
I'm not using releases, but I do compile the code ahead of time when building a docker container, so the env vars aren't available.
👍

**Comment by tompesman** [comment]
Also very helpful for Heroku deployments. 👍

**Comment by linjunpop** [comment]
For Heroku, the ENV can be made available at compile time by setting `config_vars_to_export`.

Detail: https://github.com/HashNuke/heroku-buildpack-elixir#configuration

**Comment by tompesman** [comment]
@linjunpop that's only at build time. ENV variables can change during runtime, so they need to be dynamic.

**Comment by paulanthonywilson** [comment]
Done in https://github.com/CultivateHQ/basic_auth/pull/13 (thanks @chelsea )
